# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: quickstart-existing-vpc-cluster-01
  region: us-east-2

vpc:
  id: "vpc-0cd9ef9417c2a2cd9"  # (optional, must match VPC ID used for each subnet below)
  #cidr: "172.31.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      us-east-2a:
        id: "subnet-0116937c407ce214e"
        #cidr: "192.168.128.0/19" # (optional, must match CIDR used by the given subnet)
      us-east-2b:
        id: "subnet-0557d379e8e22292a"
        #cidr: "192.168.64.0/19"  # (optional, must match CIDR used by the given subnet)

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 50
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
    ssh:
      publicKeyPath: ~/.ssh/eksctl.pub
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 100
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
    ssh:
      publicKeyPath: ~/.ssh/eksctl.pub
  - name: ng-3
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 40
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
        ebs: true
    ssh:
      publicKeyPath: ~/.ssh/eksctl.pub
    availabilityZones: ["us-east-2a", "us-east-2b"]
cloudWatch:
  clusterLogging:
      # enable specific types of cluster control plane logs
      enableTypes: ["audit", "authenticator", "controllerManager"]
      # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
      # supported special values: "*" and "all"
addons:
  - name: vpc-cni # no version is specified so it deploys the default version
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest