# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: quickstart-alb-ingress-controller-cluster-01
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 50
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
    ssh:
      publicKeyPath: ~/.ssh/eksctl.pub
cloudWatch:
  clusterLogging:
      # enable specific types of cluster control plane logs
      enableTypes: ["audit", "authenticator", "controllerManager"]
      # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
      # supported special values: "*" and "all"
addons:
  - name: vpc-cni # no version is specified so it deploys the default version
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest # auto discovers the latest available
  - name: kube-proxy
    version: latest